# Generated by Django 5.2.6 on 2025-09-30 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_remove_chatmessage_chat_friendship_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='privatechatmessage',
            name='thread_name',
        ),
        migrations.AddField(
            model_name='privatechatmessage',
            name='status',
            field=models.CharField(choices=[('sent', 'Sent'), ('delivered', 'Delivered'), ('read', 'Read')], default='sent', max_length=10),
        ),
    ]
