# Generated by Django 5.2.6 on 2025-09-30 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_remove_privatechatmessage_thread_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='privatechatmessage',
            name='status',
        ),
    ]
